POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento teste333",
  "details":"aaaaaaaaaaaaa",
  "maximumAttendees":1
}

###
POST http://localhost:3333/events/9f1994d2-464b-4a9e-9afb-c3e986ba1a46/attendees
Content-Type: application/json

{
  "name":"Breno teste",
  "email":"teste@teste111.com"
}

###
GET http://localhost:3333/events/9f1994d2-464b-4a9e-9afb-c3e986ba1a46
Content-Type: application/json
