POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento teste333",
  "details":"aaaaaaaaaaaaa",
  "maximumAttendees":1
}

###
POST http://localhost:3333/events/33130a15-9ff2-4628-b466-21d10e5e0476/attendees
Content-Type: application/json

{
  "name":"Breno teste",
  "email":"teste@teste111.com"
}

###
GET http://localhost:3333/events/33130a15-9ff2-4628-b466-21d10e5e0476

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/33130a15-9ff2-4628-b466-21d10e5e0476/attendees
